In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving CMAPSSData.zip to CMAPSSData.zip

In [3]:
import zipfile
with zipfile.ZipFile('CMAPSSData.zip', 'r') as zip_ref:
    zip_ref.extractall('CMAPSSData')

In [4]:
import os
os.listdir('CMAPSSData')

['train_FD002.txt',
 'test_FD004.txt',
 'test_FD001.txt',
 'train_FD001.txt',
 'Damage Propagation Modeling.pdf',
 'RUL_FD004.txt',
 'RUL_FD001.txt',
 'RUL_FD002.txt',
 'train_FD004.txt',
 'train_FD003.txt',
 'test_FD003.txt',
 'RUL_FD003.txt',
 'test_FD002.txt',
 'readme.txt']

In [5]:
# Read the NASA dataset documentation using a compatible encoding
with open("CMAPSSData/readme.txt", "r", encoding="latin-1") as file:
    readme = file.read()

print(readme)

Data Set: FD001
Train trjectories: 100
Test trajectories: 100
Conditions: ONE (Sea Level)
Fault Modes: ONE (HPC Degradation)

Data Set: FD002
Train trjectories: 260
Test trajectories: 259
Conditions: SIX
Fault Modes: ONE (HPC Degradation)

Data Set: FD003
Train trjectories: 100
Test trajectories: 100
Conditions: ONE (Sea Level)
Fault Modes: TWO (HPC Degradation, Fan Degradation)

Data Set: FD004
Train trjectories: 248
Test trajectories: 249
Conditions: SIX
Fault Modes: TWO (HPC Degradation, Fan Degradation)



Experimental Scenario

Data sets consists of multiple multivariate time series. Each data set is further divided into training and test subsets. Each time series is from a different engine  i.e., the data can be considered to be from a fleet of engines of the same type. Each engine starts with different degrees of initial wear and manufacturing variation which is unknown to the user. This wear and variation is considered normal, i.e., it is not considered a fault condition. There are three operational settings that have a substantial effect on engine performance. These settings are also included in the data. The data is contaminated with sensor noise.

The engine is operating normally at the start of each time series, and develops a fault at some point during the series. In the training set, the fault grows in magnitude until system failure. In the test set, the time series ends some time prior to system failure. The objective of the competition is to predict the number of remaining operational cycles before failure in the test set, i.e., the number of operational cycles after the last cycle that the engine will continue to operate. Also provided a vector of true Remaining Useful Life (RUL) values for the test data.

The data are provided as a zip-compressed text file with 26 columns of numbers, separated by spaces. Each row is a snapshot of data taken during a single operational cycle, each column is a different variable. The columns correspond to:
1)	unit number
2)	time, in cycles
3)	operational setting 1
4)	operational setting 2
5)	operational setting 3
6)	sensor measurement  1
7)	sensor measurement  2
...
26)	sensor measurement  26


Reference: A. Saxena, K. Goebel, D. Simon, and N. Eklund, Damage Propagation Modeling for Aircraft Engine Run-to-Failure Simulation, in the Proceedings of the Ist International Conference on Prognostics and Health Management (PHM08), Denver CO, Oct 2008.

In [6]:
# Load the FD001 training dataset
train_path = "CMAPSSData/train_FD001.txt"

train_raw = pd.read_csv(
    train_path,
    sep=r"\s+",
    header=None
)
train_raw.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [7]:
# Define meaningful column names for the CMAPSS dataset
columns = (
   ["unit_id","cycle"] +
   [f"setting{i}" for i in range(1,4)] +
   [f"sensor{i}" for i in range(1,22)]
)
train_raw.columns = columns

train_raw.head()

,unit_id,cycle,setting1,setting2,setting3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor12,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [8]:
# check the structure and data types of the training dataset
print("Dataset_shape:",train_raw.shape)
print("\nColumn names: ")
print(train_raw.columns.tolist())

print("\nData types:")
print(train_raw.dtypes)

Dataset_shape: (20631, 26)

Column names:
['unit_id', 'cycle', 'setting1', 'setting2', 'setting3', 'sensor1', 'sensor2', 'sensor3', 'sensor4', 'sensor5', 'sensor6', 'sensor7', 'sensor8', 'sensor9', 'sensor10', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor16', 'sensor17', 'sensor18', 'sensor19', 'sensor20', 'sensor21']

Data types:
unit_id       int64
cycle         int64
setting1    float64
setting2    float64
setting3    float64
sensor1     float64
sensor2     float64
sensor3     float64
sensor4     float64
sensor5     float64
sensor6     float64
sensor7     float64
sensor8     float64
sensor9     float64
sensor10    float64
sensor11    float64
sensor12    float64
sensor13    float64
sensor14    float64
sensor15    float64
sensor16    float64
sensor17      int64
sensor18      int64
sensor19    float64
sensor20    float64
sensor21    float64
dtype: object

In [9]:
# check the number of engines and their operating cycle ranges
print("Number of engines: ", train_raw["unit_id"].nunique())

print("\nFirst ten engine IDs :")
print(train_raw["unit_id"].unique()[:10])

print("\nMaximum cycle for each of the first 10 engines: ")
print(
    train_raw.groupby("unit_id")["cycle"].max().head(10)

)

Number of engines:  100

First ten engine IDs :
[ 1  2  3  4  5  6  7  8  9 10]

Maximum cycle for each of the first 10 engines:
unit_id
1     192
2     287
3     179
4     189
5     269
6     188
7     259
8     150
9     201
10    222
Name: cycle, dtype: int64

In [10]:
# check for missing values in each column
missing_values = train_raw.isnull().sum()
print(missing_values)

unit_id     0
cycle       0
setting1    0
setting2    0
setting3    0
sensor1     0
sensor2     0
sensor3     0
sensor4     0
sensor5     0
sensor6     0
sensor7     0
sensor8     0
sensor9     0
sensor10    0
sensor11    0
sensor12    0
sensor13    0
sensor14    0
sensor15    0
sensor16    0
sensor17    0
sensor18    0
sensor19    0
sensor20    0
sensor21    0
dtype: int64

In [11]:
# check how much sensor varies across the training data
sensor_columns = [f"sensor{i}" for i in range(1,22)]
sensor_variance = train_raw[sensor_columns].var()
print(sensor_variance)

sensor1     4.273435e-21
sensor2     2.500533e-01
sensor3     3.759099e+01
sensor4     8.101089e+01
sensor5     1.152399e-23
sensor6     1.929279e-06
sensor7     7.833883e-01
sensor8     5.038938e-03
sensor9     4.876536e+02
sensor10    2.172333e-25
sensor11    7.133568e-02
sensor12    5.439850e-01
sensor13    5.172330e-03
sensor14    3.639005e+02
sensor15    1.406628e-03
sensor16    2.422479e-28
sensor17    2.398667e+00
sensor18    0.000000e+00
sensor19    0.000000e+00
sensor20    3.266927e-02
sensor21    1.171825e-02
dtype: float64

In [12]:
# Inspect the unique values of sensors with near-zero variance

constant_sensor_candidates = [
    "sensor1","sensor5","sensor10","sensor16","sensor18","sensor19"
]

for sensor in constant_sensor_candidates:
    print(f"{sensor}: {train_raw[sensor].unique()}")

sensor1: [518.67]
sensor5: [14.62]
sensor10: [1.3]
sensor16: [0.03]
sensor18: [2388]
sensor19: [100.]

In [13]:
# remove constant sensors that provide no variation in this dataset(FD001)

constant_sensors = [
    "sensor1","sensor5","sensor10","sensor16","sensor18","sensor19"
]
train_processed = train_raw.drop(columns=constant_sensors)

print("original shape: " ,train_raw.shape)
print("processed shape: ",train_processed.shape)

original shape:  (20631, 26)
processed shape:  (20631, 20)

In [14]:
# check for duplicate rows in processed dataset

duplicate_count = train_processed.duplicated().sum()
print("No of duplicate rows: " , duplicate_count)

No of duplicate rows:  0

In [15]:
# inspect the range of the remaining numerical features

feature_summary = train_processed.describe().T[["min","max","mean","std"]]

print(feature_summary)

                min        max         mean        std
unit_id      1.0000   100.0000    51.506568  29.227633
cycle        1.0000   362.0000   108.807862  68.880990
setting1    -0.0087     0.0087    -0.000009   0.002187
setting2    -0.0006     0.0006     0.000002   0.000293
setting3   100.0000   100.0000   100.000000   0.000000
sensor2    641.2100   644.5300   642.680934   0.500053
sensor3   1571.0400  1616.9100  1590.523119   6.131150
sensor4   1382.2500  1441.4900  1408.933782   9.000605
sensor6     21.6000    21.6100    21.609803   0.001389
sensor7    549.8500   556.0600   553.367711   0.885092
sensor8   2387.9000  2388.5600  2388.096652   0.070985
sensor9   9021.7300  9244.5900  9065.242941  22.082880
sensor11    46.8500    48.5300    47.541168   0.267087
sensor12   518.6900   523.3800   521.413470   0.737553
sensor13  2387.8800  2388.5600  2388.096152   0.071919
sensor14  8099.9400  8293.7200  8143.752722  19.076176
sensor15     8.3249     8.5848     8.442146   0.037505
sensor17   388.0000   400.0000   393.210654   1.548763
sensor20    38.1400    39.4300    38.816271   0.180746
sensor21    22.8942    23.6184    23.289705   0.108251

In [16]:
# remove the constant operating setting from the processed dataset

train_processed = train_processed.drop(columns = ["setting3"])
print("processed shape: ", train_processed.shape)

processed shape:  (20631, 19)

In [17]:
# inspect the distributions of remaining numerical features

train_processed.describe().T

,count,mean,std,min,25%,50%,75%,max
unit_id,20631.0,51.506568,29.227633,1.0000,26.0000,52.0000,77.0000,100.0000
cycle,20631.0,108.807862,68.880990,1.0000,52.0000,104.0000,156.0000,362.0000
setting1,20631.0,-0.000009,0.002187,-0.0087,-0.0015,0.0000,0.0015,0.0087
setting2,20631.0,0.000002,0.000293,-0.0006,-0.0002,0.0000,0.0003,0.0006
sensor2,20631.0,642.680934,0.500053,641.2100,642.3250,642.6400,643.0000,644.5300
sensor3,20631.0,1590.523119,6.131150,1571.0400,1586.2600,1590.1000,1594.3800,1616.9100
sensor4,20631.0,1408.933782,9.000605,1382.2500,1402.3600,1408.0400,1414.5550,1441.4900
sensor6,20631.0,21.609803,0.001389,21.6000,21.6100,21.6100,21.6100,21.6100
sensor7,20631.0,553.367711,0.885092,549.8500,552.8100,553.4400,554.0100,556.0600
sensor8,20631.0,2388.096652,0.070985,2387.9000,2388.0500,2388.0900,2388.1400,2388.5600
sensor9,20631.0,9065.242941,22.082880,9021.7300,9053.1000,9060.6600,9069.4200,9244.5900
sensor11,20631.0,47.541168,0.267087,46.8500,47.3500,47.5100,47.7000,48.5300
sensor12,20631.0,521.413470,0.737553,518.6900,520.9600,521.4800,521.9500,523.3800
sensor13,20631.0,2388.096152,0.071919,2387.8800,2388.0400,2388.0900,2388.1400,2388.5600
sensor14,20631.0,8143.752722,19.076176,8099.9400,8133.2450,8140.5400,8148.3100,8293.7200
sensor15,20631.0,8.442146,0.037505,8.3249,8.4149,8.4389,8.4656,8.5848
sensor17,20631.0,393.210654,1.548763,388.0000,392.0000,393.0000,394.0000,400.0000
sensor20,20631.0,38.816271,0.180746,38.1400,38.7000,38.8300,38.9500,39.4300
sensor21,20631.0,23.289705,0.108251,22.8942,23.2218,23.2979,23.3668,23.6184

In [18]:
# identify potential outliers using IQR method

feature_columns = [
    col for col in train_processed.columns
    if col not in ["unit_id", "cycle"]
]

Q1 = train_processed[feature_columns].quantile(0.25)
Q3 = train_processed[feature_columns].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_counts = (
    (train_processed[feature_columns] < lower_bound)|
    (train_processed[feature_columns] > upper_bound)
).sum()

print("Potential outlier counts:")
print(outlier_counts)

Potential outlier counts:
setting1     105
setting2       0
sensor2      128
sensor3      165
sensor4      120
sensor6      406
sensor7      110
sensor8      320
sensor9     1686
sensor11     167
sensor12     146
sensor13     161
sensor14    1543
sensor15     120
sensor17      81
sensor20     117
sensor21     136
dtype: int64

In [19]:
# calculate the maximum operating cycle for each engine

max_cycle_per_engine = (train_processed.groupby("unit_id")["cycle"].max()
)
print(max_cycle_per_engine)

unit_id
1      192
2      287
3      179
4      189
5      269
      ...
96     336
97     202
98     156
99     185
100    200
Name: cycle, Length: 100, dtype: int64

In [78]:
# Calculate Remaining Useful Life (RUL) for each observation


max_cycle_per_engine = (
    train_processed.groupby("unit_id")["cycle"].max()
)

train_processed["RUL_raw"] = (
    train_processed["unit_id"].map(max_cycle_per_engine)
    - train_processed["cycle"]
)

RUL_CAP = 125

train_processed["RUL"] = (
    train_processed["RUL_raw"].clip(upper=RUL_CAP)
)

print("RUL cap:", RUL_CAP)
print("Raw RUL maximum:", train_processed["RUL_raw"].max())
print("Capped RUL maximum:", train_processed["RUL"].max())

display(
    train_processed[
        ["unit_id", "cycle", "RUL_raw", "RUL"]
    ].head(10)
)

RUL cap: 125
Raw RUL maximum: 361
Capped RUL maximum: 125

   unit_id  cycle  RUL_raw  RUL
0        1      1      191  125
1        1      2      190  125
2        1      3      189  125
3        1      4      188  125
4        1      5      187  125
5        1      6      186  125
6        1      7      185  125
7        1      8      184  125
8        1      9      183  125
9        1     10      182  125

In [21]:
# calculate a five cycle rolling mean for sensor3 within each engine

train_processed["sensor3_rolling_mean"] = (
    train_processed.groupby("unit_id")["sensor3"].transform
    (lambda x : x.rolling(window=5, min_periods=1).mean())
)

train_processed[
    ["unit_id","cycle","sensor3_rolling_mean"]
].head(10)

   unit_id  cycle  sensor3_rolling_mean
0        1      1           1589.700000
1        1      2           1590.760000
2        1      3           1589.836667
3        1      4           1588.075000
4        1      5           1587.030000
5        1      6           1585.984000
6        1      7           1586.084000
7        1      8           1585.078000
8        1      9           1586.716000
9        1     10           1588.394000

In [22]:
# Verify that the rolling feature was added successfully

print("New feature:", "sensor3_rolling_mean" in train_processed.columns)
print("Number of columns:", len(train_processed.columns))

New feature: True
Number of columns: 22

In [23]:
def add_rolling_mean_features(df,sensor_columns,window = 5):

    df = df.copy()

    for sensor in sensor_columns:
        feature_name = f"{sensor}_rolling_mean"

        df[feature_name] = (
            df.groupby("unit_id")[sensor].transform(
                lambda x : x.rolling(
                    window=window,
                    min_periods=1
                ).mean()
            )
        )
    return df

In [24]:
# Select the sensors that remain after constabt feature removal

sensor_columns = [
    col for col in train_processed.columns
    if col.startswith("sensor") and not col.endswith("rolling_mean")
]

print(sensor_columns)

['sensor2', 'sensor3', 'sensor4', 'sensor6', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21']

In [25]:
# Generate 5-cycle rolling mean features for all varying sensors

trained_processed = add_rolling_mean_features(
    train_processed,
    sensor_columns,
    window = 5

)
print("updated shape: ",trained_processed.shape)

updated shape:  (20631, 36)

In [26]:
# identify all rolling mean features that were created

rolling_mean_columns = [
    col for col in trained_processed.columns
    if col.endswith("_rolling_mean")
]

print("Number of rolling mesn features: " ,len(rolling_mean_columns))
print("\nRolling-mean features: ")
print(rolling_mean_columns)

Number of rolling mesn features:  15

Rolling-mean features:
['sensor3_rolling_mean', 'sensor2_rolling_mean', 'sensor4_rolling_mean', 'sensor6_rolling_mean', 'sensor7_rolling_mean', 'sensor8_rolling_mean', 'sensor9_rolling_mean', 'sensor11_rolling_mean', 'sensor12_rolling_mean', 'sensor13_rolling_mean', 'sensor14_rolling_mean', 'sensor15_rolling_mean', 'sensor17_rolling_mean', 'sensor20_rolling_mean', 'sensor21_rolling_mean']

In [27]:
def add_rolling_std_features(df,sensor_columns,window = 5):

    df = df.copy()

    for sensor in sensor_columns:
        feature_name = f"{sensor}_rolling_std"

        df[feature_name] = (
            df.groupby("unit_id")[sensor]
            .transform(lambda x : x.rolling(
                window=window,
                min_periods=1
            ).std()

          )

        )
    return df

In [28]:
# Generate 5-cycle rolling standard deviation features

train_processed = add_rolling_std_features(
    train_processed,
    sensor_columns,
    window=5
)

print("Updated shape:", train_processed.shape)

Updated shape: (20631, 37)

In [29]:
# Check which sensors are currently stored in sensor_columns

print("Number of sensors:", len(sensor_columns))
print("Sensors:", sensor_columns)

Number of sensors: 15
Sensors: ['sensor2', 'sensor3', 'sensor4', 'sensor6', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21']

In [30]:
# Check which rolling-standard-deviation features currently exist

rolling_std_columns = [
    col for col in train_processed.columns
    if col.endswith("_rolling_std")
]

print("Number of rolling-std features:", len(rolling_std_columns))
print("\nRolling-std features:")
print(rolling_std_columns)

Number of rolling-std features: 15

Rolling-std features:
['sensor2_rolling_std', 'sensor3_rolling_std', 'sensor4_rolling_std', 'sensor6_rolling_std', 'sensor7_rolling_std', 'sensor8_rolling_std', 'sensor9_rolling_std', 'sensor11_rolling_std', 'sensor12_rolling_std', 'sensor13_rolling_std', 'sensor14_rolling_std', 'sensor15_rolling_std', 'sensor17_rolling_std', 'sensor20_rolling_std', 'sensor21_rolling_std']

In [31]:
print("Current dataset shape:", train_processed.shape)

print("\nOriginal + target columns:")
print([
    col for col in train_processed.columns
    if not col.endswith("_rolling_mean")
    and not col.endswith("_rolling_std")
])

Current dataset shape: (20631, 37)

Original + target columns:
['unit_id', 'cycle', 'setting1', 'setting2', 'sensor2', 'sensor3', 'sensor4', 'sensor6', 'sensor7', 'sensor8', 'sensor9', 'sensor11', 'sensor12', 'sensor13', 'sensor14', 'sensor15', 'sensor17', 'sensor20', 'sensor21', 'RUL_raw', 'RUL']

In [32]:
# Count each type of column currently in the dataset

base_columns = [
    col for col in train_processed.columns
    if not col.endswith("_rolling_mean")
    and not col.endswith("_rolling_std")
]

rolling_mean_columns = [
    col for col in train_processed.columns
    if col.endswith("_rolling_mean")
]

rolling_std_columns = [
    col for col in train_processed.columns
    if col.endswith("_rolling_std")
]

print("Base columns:", len(base_columns))
print("Rolling mean columns:", len(rolling_mean_columns))
print("Rolling std columns:", len(rolling_std_columns))

print("\nTotal according to categories:",
      len(base_columns) + len(rolling_mean_columns) + len(rolling_std_columns))

print("\nActual DataFrame columns:", len(train_processed.columns))

Base columns: 21
Rolling mean columns: 1
Rolling std columns: 15

Total according to categories: 37

Actual DataFrame columns: 37

In [33]:
# Add any missing rolling-mean features

for sensor in sensor_columns:
    feature_name = f"{sensor}_rolling_mean"

    if feature_name not in train_processed.columns:
        train_processed[feature_name] = (
            train_processed
            .groupby("unit_id")[sensor]
            .transform(
                lambda x: x.rolling(
                    window=5,
                    min_periods=1
                ).mean()
            )
        )

print("Dataset shape after fixing rolling means:", train_processed.shape)

Dataset shape after fixing rolling means: (20631, 51)

In [34]:
# Final verification of engineered feature groups

base_columns = [
    col for col in train_processed.columns
    if not col.endswith("_rolling_mean")
    and not col.endswith("_rolling_std")
]

rolling_mean_columns = [
    col for col in train_processed.columns
    if col.endswith("_rolling_mean")
]

rolling_std_columns = [
    col for col in train_processed.columns
    if col.endswith("_rolling_std")
]

print("Base columns:", len(base_columns))
print("Rolling mean features:", len(rolling_mean_columns))
print("Rolling std features:", len(rolling_std_columns))
print("Total columns:", len(train_processed.columns))

Base columns: 21
Rolling mean features: 15
Rolling std features: 15
Total columns: 51

In [35]:
# Check missing values in rolling standard deviation features

rolling_std_missing = train_processed[rolling_std_columns].isnull().sum()

print("Missing values in rolling-std features:")
print(rolling_std_missing)

print("\nTotal missing values:", rolling_std_missing.sum())

Missing values in rolling-std features:
sensor2_rolling_std     100
sensor3_rolling_std     100
sensor4_rolling_std     100
sensor6_rolling_std     100
sensor7_rolling_std     100
sensor8_rolling_std     100
sensor9_rolling_std     100
sensor11_rolling_std    100
sensor12_rolling_std    100
sensor13_rolling_std    100
sensor14_rolling_std    100
sensor15_rolling_std    100
sensor17_rolling_std    100
sensor20_rolling_std    100
sensor21_rolling_std    100
dtype: int64

Total missing values: 1500

In [36]:
# Fill initial rolling-standard-deviation NaN values with 0

train_processed[rolling_std_columns] = (
    train_processed[rolling_std_columns].fillna(0)
)

print(
    "Remaining missing values in rolling-std features:",
    train_processed[rolling_std_columns].isnull().sum().sum()
)

Remaining missing values in rolling-std features: 0

In [37]:
# Calculate the cycle-to-cycle change for sensor3

train_processed["sensor3_rate_of_change"] = (
    train_processed
    .groupby("unit_id")["sensor3"]
    .diff()
)

train_processed[
    ["unit_id", "cycle", "sensor3", "sensor3_rate_of_change"]
].head(10)

   unit_id  cycle  sensor3  sensor3_rate_of_change
0        1      1  1589.70                     NaN
1        1      2  1591.82                    2.12
2        1      3  1587.99                   -3.83
3        1      4  1582.79                   -5.20
4        1      5  1582.85                    0.06
5        1      6  1584.47                    1.62
6        1      7  1592.32                    7.85
7        1      8  1582.96                   -9.36
8        1      9  1590.98                    8.02
9        1     10  1591.24                    0.26

In [38]:
def add_rate_of_change_features(df, sensor_columns):

   df = df.copy()

   for sensor in sensor_columns:
        feature_name = f"{sensor}_rate_of_change"

        df[feature_name] = (
            df.groupby("unit_id")[sensor]
            .diff()
        )

   return df

In [39]:
# Generate rate-of-change features for all varying sensors

train_processed = add_rate_of_change_features(
    train_processed,
    sensor_columns
)

print("Updated shape:", train_processed.shape)

Updated shape: (20631, 66)

In [40]:
# Verify all rate-of-change features

rate_of_change_columns = [
    col for col in train_processed.columns
    if col.endswith("_rate_of_change")
]

print("Number of rate-of-change features:", len(rate_of_change_columns))
print("\nRate-of-change features:")
print(rate_of_change_columns)

Number of rate-of-change features: 15

Rate-of-change features:
['sensor3_rate_of_change', 'sensor2_rate_of_change', 'sensor4_rate_of_change', 'sensor6_rate_of_change', 'sensor7_rate_of_change', 'sensor8_rate_of_change', 'sensor9_rate_of_change', 'sensor11_rate_of_change', 'sensor12_rate_of_change', 'sensor13_rate_of_change', 'sensor14_rate_of_change', 'sensor15_rate_of_change', 'sensor17_rate_of_change', 'sensor20_rate_of_change', 'sensor21_rate_of_change']

In [41]:
# Check missing values in rate-of-change features

rate_of_change_missing = (
    train_processed[rate_of_change_columns]
    .isnull()
    .sum()
)

print("Missing values in rate-of-change features:")
print(rate_of_change_missing)

print("\nTotal missing values:", rate_of_change_missing.sum())

Missing values in rate-of-change features:
sensor3_rate_of_change     100
sensor2_rate_of_change     100
sensor4_rate_of_change     100
sensor6_rate_of_change     100
sensor7_rate_of_change     100
sensor8_rate_of_change     100
sensor9_rate_of_change     100
sensor11_rate_of_change    100
sensor12_rate_of_change    100
sensor13_rate_of_change    100
sensor14_rate_of_change    100
sensor15_rate_of_change    100
sensor17_rate_of_change    100
sensor20_rate_of_change    100
sensor21_rate_of_change    100
dtype: int64

Total missing values: 1500

In [42]:
# Fill initial rate-of-change NaN values with 0

train_processed[rate_of_change_columns] = (
    train_processed[rate_of_change_columns].fillna(0)
)

print(
    "Remaining missing values in rate-of-change features:",
    train_processed[rate_of_change_columns].isnull().sum().sum()
)

Remaining missing values in rate-of-change features: 0

In [43]:
# Perform a complete missing-value audit

missing_values = train_processed.isnull().sum()

print("Total missing values in dataset:", missing_values.sum())

print("\nColumns containing missing values:")
print(missing_values[missing_values > 0])

Total missing values in dataset: 0

Columns containing missing values:
Series([], dtype: int64)